#!/bin/bash
#
# Script to create a Storage Account configured for SFTP
#

# Deploy Resources
az group create --name SftpStorage \
                --location centralus

az deployment group create --name SftpStorageAccountDeployment \
                           --resource-group SftpStorage \
                           --template-file sftp-storage-account.bicep \
                           --parameters @sftp-storage-account.parameters.json

# Confirm Resources
az deployment group show --name SftpStorageAccountDeployment \
                         --resource-group SftpStorage
